version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  allow:
  - dependency-name: "@ecomplus/storefront-template"
  ignore:
  - dependency-name: "@ecomplus/storefront-template"
    versions:
    - 2.0.0-beta.111
    - 2.0.0-beta.112
    - 2.0.0-beta.113
    - 2.0.0-beta.114
    - 2.0.0-beta.115
    - 2.0.0-beta.116
    - 2.0.0-beta.117
    - 2.0.0-beta.118
    - 2.0.0-beta.120
  commit-message:
    prefix: fix
    include: scope
