[[redirects]]
  from = "/grid/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/content/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/marca/*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/contate-nos"
  to = "/index"
  status = 301
  
  [[redirects]]
  from = "/pagina/*"
  to = "/index"
  status = 301
